language: python
python:
  - "3.5"
  - "3.6"

before_install:
  - sudo add-apt-repository -y ppa:neovim-ppa/unstable
  - sudo apt-get -qq update
  - sudo apt-get -qq -f install
  - sudo apt-get -qq install neovim

install:
  - pip install -r requirements.txt

script:
  - pytest -v
